### ISSUE TITLE
DeviceManagement.Enrolment is using incorrect locallization.

### ISSUE THREAD

**Issue by sofbkeller** [MicrosoftDocs/microsoftgraph-docs-powershell#149]
The Microsoft.Graph.DeviceManagement.Enrolment module in Microsoft Graph Powershell is using the incorrect localization for EN-US which is what powershell modules are based on in my understanding. This break from the norm is confusing and incorrect in EN-US/EN-CA where it is spelled "Enrollment".
Enrolment is a UK localization of the same word.

Direct link to module markdown file:
https://github.com/MicrosoftDocs/microsoftgraph-docs-powershell/tree/e846405e1e66af99a2463e7da477c77cc5505b66/microsoftgraph/graph-powershell-1.0/Microsoft.Graph.DeviceManagement.Enrolment)/Microsoft.Graph.DeviceManagement.Enrolment.md

**Comment by msewaweru** [comment]
@sofbkeller transferred this issue to the SDK repo for advice. https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/1913
