### ISSUE TITLE
A set of cmdlets that have the error 'Disallowed HTML tag' when we build any PRs.

### ISSUE THREAD

**Issue by msewaweru** [MicrosoftDocs/microsoftgraph-docs-powershell#180]
![image](https://user-images.githubusercontent.com/73849846/210569528-d257292a-ad3c-44a2-bfb0-7a102ba4dd8c.png)

**Comment by Loyalty84** [comment]
> ![image](https://user-images.githubusercontent.com/73849846/210569528-d257292a-ad3c-44a2-bfb0-7a102ba4dd8c.png)
