### ISSUE TITLE
MS Graph API - Update user license service plan provisioningStatus using "Update-MgUserLicenseDetail"

### ISSUE THREAD

**Issue by Hec-gitHub** [MicrosoftDocs/microsoftgraph-docs-powershell#233]
Hello, I want to change a service plan status (Disabled->Success) in the specified user license plan.
 However, Update-MgUserLicenseDetail command raises an Error.
The execution process is as follows:
$skuId='xxx'
$servicePlanId='xxx'
$servicePlanName='xxx'
$licenseDetailsId='xxx' 
$servicePlans=@{AppliesTo="User"
                ProvisioningStatus="Success"
                ServicePlanId=$servicePlanId
                ServicePlanName=$servicePlanName}
$params=@{ServicePlans= $servicePlans
	            SkuId = $skuId}

Update-MgUserLicenseDetail -UserId 'xxx' -LicenseDetailsId $licenseDetailsId -BodyParameter $params

The error:
Update-MgUserLicenseDetail : Filtered searches against this resource are not supported.

Is there something wrong with the way to use Update-MgUserLicenseDetail .

**Comment by Hec-gitHub** [comment]
@msewaweru -Thank you very much for your reply
Using the  [Set-MgUserLicense](https://learn.microsoft.com/en-us/powershell/module/microsoft.graph.users.actions/set-mguserlicense?view=graph-powershell-1.0) can achieve additional licenses, delete licenses, and disable certain service plans in the license.
I want to enable some disabled services in my license again. Using the [Set-MgUserLicense](https://learn.microsoft.com/en-us/powershell/module/microsoft.graph.users.actions/set-mguserlicense?view=graph-powershell-1.0) command, I don't know how to implement it.

**Comment by DamagedDingo** [comment]
For future reference to enable disabled services you can use the script below, but the main ingredient is to use "Success" not "Enable"

`$fullUser = Get-MgUser -UserId $UserUPN

$EmsSku = Get-MgSubscribedSku -All | Where SkuPartNumber -eq 'M365EDU_A5_FACULTY'
$userLicense = Get-MgUserLicenseDetail -UserId $fullUser.id

$userEnabledPlans = $userLicense.ServicePlans |
Where ProvisioningStatus -eq "Success" |
Select -ExpandProperty ServicePlanId

$newEnabledPlans = $EmsSku.ServicePlans |
Where ServicePlanName -in ("Bing_Chat_Enterprise") |
Select -ExpandProperty ServicePlanId

$enabledPlans = $userEnabledPlans + $newEnabledPlans | Select -Unique

$addLicenses = @(
    @{SkuId           = $EmsSku.SkuId
        DisabledPlans = $disabledPlans
    }
)

Set-MgUserLicense -UserId $fullUser.Id -AddLicenses $addLicenses -RemoveLicenses @()`
