### ISSUE TITLE
Stale Cmdlet Reference Docs

### ISSUE THREAD

**Issue by peombwa** [MicrosoftDocs/microsoftgraph-docs-powershell#234]
It looks like the cmdlet reference docs haven't been updated in a while. For example: `Get-MgTeam` no longer supports list parameter set (`-All`) in v1.0. However, the reference docs currently show the command having list parameter set (`-All`) - https://learn.microsoft.com/en-us/powershell/module/microsoft.graph.teams/get-mgteam?view=graph-powershell-1.0. The list variant is not present in the offline help:
![image](https://user-images.githubusercontent.com/7061532/228636808-a4391b98-4232-46ed-8641-e847e27e7ad7.png)

cc\ @timayabi2020

**Comment by peombwa** [comment]
Can we do a new rerun to purge old cmdlets and update existing cmdlets? This should ideally happen once per week to sync the reference docs to what's available in the SDK.

**Comment by timayabi2020** [comment]
> Can we do a new rerun to purge old cmdlets and update existing cmdlets? This should ideally happen once per week to sync the reference docs to what's available in the SDK.

The pipeline will run tomorrow. I'll manually create a PR from the new branch that will be created from that run.

**Comment by apz100** [comment]
i find it a bit silly this command is missing and would be so much easier to find a team's ID among other properties rather than going into AAD to remember which group ID etc is associated with the team

**Comment by peombwa** [comment]
@apz100, listing of teams is not supported by the API in v1.0 - https://learn.microsoft.com/en-us/graph/teams-list-all-teams?context=graph%2Fapi%2F1.0&view=graph-rest-1.0.
> To use the Microsoft Teams API in Microsoft Graph to list all [teams](https://learn.microsoft.com/en-us/graph/api/resources/team) in an organization (tenant), you find all groups that have teams, and then get information for each team.

The commands in this module will only support what's supported by the REST API. Please open/ upvote on a feature request for the API owner at https://developer.microsoft.com/en-us/graph/support.
