### ISSUE TITLE
Set-MgUserLicense cmdlet in v1.0 doe not get the description similar to the beta version.

### ISSUE THREAD

**Issue by msewaweru** [MicrosoftDocs/microsoftgraph-docs-powershell#236]
![image](https://user-images.githubusercontent.com/73849846/228845203-92c4e601-496c-48a6-a6a8-c7c4b17a1e25.png)

**Comment by timayabi2020** [comment]
@msewaweru the descriptions on the PowerShell reference docs reflect what is available on the api reference docs. See below.
**V1**
API [reference](https://learn.microsoft.com/en-us/graph/api/presence-setpresence?view=graph-rest-1.0&tabs=powershell)
![image](https://user-images.githubusercontent.com/10947120/229203056-a07dc1e7-668a-4e10-8fc4-0ce002663eb6.png)


_PowerShell Reference_
![image](https://user-images.githubusercontent.com/10947120/229201771-e12929a2-151b-4ded-88fa-934130218207.png)

**Beta**
Api [reference](https://learn.microsoft.com/en-us/graph/api/presence-setpresence?view=graph-rest-beta&tabs=powershell)

![image](https://user-images.githubusercontent.com/10947120/229202709-8d5742ec-34cb-4f3f-a818-a424ec7aec0f.png)

_PowerShell Reference_
![image](https://user-images.githubusercontent.com/10947120/229201288-789f7a05-1a0c-476f-8d96-29d275606c61.png)

**Comment by msewaweru** [comment]
@timayabi2020, the issue is with the Set-MgUserLicense cmdlet not Set-MgUserPresence. See below:

![image](https://github.com/MicrosoftDocs/microsoftgraph-docs-powershell/assets/73849846/2e69cde3-245f-4aa0-843e-6764165173bd)



![image](https://github.com/MicrosoftDocs/microsoftgraph-docs-powershell/assets/73849846/f5ab04cc-c231-4022-aa15-dcec36fc8cb2)

Same issue applies to the beta cmdlet.

**Comment by msewaweru** [comment]
Confirmed that the descriptions from the Graph API for v1.0 and beta has slightly different.

<img width="737" alt="image" src="https://github.com/MicrosoftDocs/microsoftgraph-docs-powershell/assets/73849846/aa454ff2-51e5-4d69-a273-f2a4efc3de23">


<img width="690" alt="image" src="https://github.com/MicrosoftDocs/microsoftgraph-docs-powershell/assets/73849846/97aa8e5b-e110-44ae-9171-13af79318b07">
