### ISSUE TITLE
Notes section for Get-MgDeviceManagementDetectedApp is confusing/unclear

### ISSUE THREAD

**Issue by JLambEJG** [MicrosoftDocs/microsoftgraph-docs-powershell#246]
The article is lacking any examples. As far as I can understand, the "-InputObject" parameter expects a hash table with some of the key value pairs documented in the "[Notes](https://learn.microsoft.com/en-us/powershell/module/microsoft.graph.devicemanagement/get-mgdevicemanagementdetectedapp?view=graph-powershell-beta#notes)" section. The command is supposed to return discovered apps for a specified device. I created the inputObj like this:

`$Device = Get-MgDeviceManagementManagedDevice -Filter "DeviceName eq '$env:computername'" -Property Id,DeviceName`
`$inputObj = @{ ManagedDeviceId = $Device.id }`
`$DeviceApps = Get-MgDeviceManagementDetectedApp -InputObject $inputObj`

However, when executed, it always throws these two errors:

- Get-MgDeviceManagementDetectedApp_GetViaIdentity: {script name} {$DeviceApps = line above} The pipeline has stopped
- Get-MgDeviceManagementDetectedApp_GetViaIdentity: {script name} {$DeviceApps = line above} InputObject has null value for InputObject.DetectedAppId

The second bullet implies that I need to pass an App's ID, when the purpose of the command is to retrieve discovered apps for a device.

Please add examples and identify any required key pairs for the input object.

**Comment by msewaweru** [comment]
@JLambEJG - thanks for highlighting this issue. 

We'll follow up with the API owner to get the HTTP example converted to PowerShell before importing the same to the PowerShell docs. In the meantime, please try using [Invoke-MgGraphRequest](https://learn.microsoft.com/en-us/powershell/microsoftgraph/authentication-commands?view=graph-powershell-1.0#using-invoke-mggraphrequest) to run the [API example](https://learn.microsoft.com/en-us/graph/api/intune-devices-detectedapp-get?view=graph-rest-1.0#example) directly.

The notes section is autogenerated from the APIs and the team is working to get a way to make the section more friendly. Thanks.
