### ISSUE TITLE
Redundant literal \n on some pages

### ISSUE THREAD

**Issue by orbanbalage** [MicrosoftDocs/microsoftgraph-docs-powershell#282]
There are 12 files that have the `\n` character inline in the text: https://github.com/search?q=repo%3AMicrosoftDocs%2Fmicrosoftgraph-docs-powershell+%22%5Cn%22+language%3AMarkdown&type=code&l=Markdown

I believe these should be removed, and I will try to create a pull request to do that if I can.

**Comment by msewaweru** [comment]
Thanks @orbanbalage for highlighting this issue. Since this is autogenerated content, please don't create a PR as the changes might be overwritten during the next content update. 

@timayabi2020, please check to solve this at the generation point. Thanks.

**Comment by orbanbalage** [comment]
Thanks - I saw other commits on the markdown files elsewhere. I don't have the CLA yet - but PR already created, sorry 😇
https://github.com/MicrosoftDocs/microsoftgraph-docs-powershell/pull/283

**Comment by msewaweru** [comment]
@timayabi2020 -polite reminder to resolve this issue.

**Comment by timayabi2020** [comment]
The issue is being worked on
