### ISSUE TITLE
`Invoke-MgInvalidateUserRefreshToken` should be renamed to `Revoke-MgUserSignInSession`

### ISSUE THREAD

**Issue by peombwa** [MicrosoftDocs/microsoftgraph-docs-powershell#284]
`Invoke-MgInvalidateUserRefreshToken` should be renamed to `Revoke-MgUserSignInSession` in the [AzureAD-MSOnline cmdlet map document](https://learn.microsoft.com/en-us/powershell/microsoftgraph/azuread-msoline-cmdlet-map?view=graph-powershell-1.0#users). The API owner replaced `InvalidateAllRefreshTokens` API with `revokeSignInSessions` back in 2019 - https://devblogs.microsoft.com/microsoft365dev/breaking-change-invalidate-all-refresh-tokens-update-in-microsoft-graph-beta/. `InvalidateAllRefreshTokens` is only available in beta, while `revokeSignInSessions` is available in both v1.0 and beta.

See the discussion at https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/2003 for more details.

**Comment by msewaweru** [comment]
Thank you, @peombwa for bringing this to my attention. I will action accordingly.
