### ISSUE TITLE
Please update "Limitations" statement about searching users/groups

### ISSUE THREAD

**Issue by joshtransient** [MicrosoftDocs/microsoftgraph-docs-powershell#296]
The first item in *Limitations* states:
> There isn't yet an equivalent of -SearchString for Get-AzureADUser and Get-AzureADGroup commands...

`Get-MgUser` and `Get-MgGroup` both support the `-Search` argument when used with `-ConsistencyLevel eventual`.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 91a73899-203d-ccf8-0298-4c9d50315862
* Version Independent ID: 27d88335-54fd-013c-2420-e197c2b17e7a
* Content: [Migrate from Azure AD PowerShell to Microsoft Graph PowerShell.](https://learn.microsoft.com/en-us/powershell/microsoftgraph/migration-steps?view=graph-powershell-1.0)
* Content Source: [microsoftgraph/docs-conceptual/migration-steps.md](https://github.com/MicrosoftDocs/microsoftgraph-docs-powershell/blob/live/microsoftgraph/docs-conceptual/migration-steps.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph-powershell**
* GitHub Login: @msewaweru
* Microsoft Alias: **eunicewaweru**

**Comment by msewaweru** [comment]
Thanks, @joshtransient for highlighting this issue. I will action accordingly.

**Comment by msewaweru** [comment]
Proceeding to close this issue with the merged PR.
