### ISSUE TITLE
Use Where-Object instead of For-Each/if

### ISSUE THREAD

**Issue by DanielGallop** [MicrosoftDocs/microsoftgraph-docs-powershell#302]
The uninstall commands under [Uninstalling the SDK](https://learn.microsoft.com/en-us/powershell/microsoftgraph/installation?view=graph-powershell-1.0#uninstalling-the-sdk) could be tidied up by using a Where-Object cmdlet instead of For-Each and an if statement.

```Powershell
Get-InstalledModule Microsoft.Graph.* | ? Name -ne "Microsoft.Graph.Authentication" | Uninstall-Module
```

instead of 

```Powershell
Get-InstalledModule Microsoft.Graph.* | %{ if($_.Name -ne "Microsoft.Graph.Authentication"){ Uninstall-Module $_.Name } }
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cfa0d6a2-8795-2d70-8282-4ab8169c8b70
* Version Independent ID: 80d8d30e-9bc3-87c1-1f8f-70850a787b3c
* Content: [Install the Microsoft Graph PowerShell SDK](https://learn.microsoft.com/en-us/powershell/microsoftgraph/installation?view=graph-powershell-1.0)
* Content Source: [microsoftgraph/docs-conceptual/installation.md](https://github.com/MicrosoftDocs/microsoftgraph-docs-powershell/blob/live/microsoftgraph/docs-conceptual/installation.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph-powershell**
* GitHub Login: @msewaweru
* Microsoft Alias: **eunicewaweru**

**Comment by msewaweru** [comment]
@DanielGallop - thanks for the great suggestion. I will adopt it.

**Comment by msewaweru** [comment]
I have updated an existing PR on the same article with this change and it will be merged soon. Thanks again.
