### ISSUE TITLE
Cmdlets for privileged role assignment missing

### ISSUE THREAD

**Issue by buffytepper** [MicrosoftDocs/microsoftgraph-docs-powershell#304]
[Enter feedback here]

There are cmdlets from the Azure AD Preview, namely around privilege role assignments. What are the Microsoft Graph equivalents of these? 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: dada1864-4eb3-a28d-7894-af6d352a0f54
* Version Independent ID: 4f4e8d2f-85ad-06bd-aee2-797f2b921a0a
* Content: [Find Azure AD and MSOnline cmdlets in Microsoft Graph PowerShell](https://learn.microsoft.com/en-us/powershell/microsoftgraph/azuread-msoline-cmdlet-map?view=graph-powershell-1.0#msonline-to-microsoft-graph-powershell)
* Content Source: [microsoftgraph/docs-conceptual/azuread-msoline-cmdlet-map.md](https://github.com/MicrosoftDocs/microsoftgraph-docs-powershell/blob/live/microsoftgraph/docs-conceptual/azuread-msoline-cmdlet-map.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph-powershell**
* GitHub Login: @msewaweru
* Microsoft Alias: **eunicewaweru**

**Comment by msewaweru** [comment]
Hello @buffytepper - thanks for your question. We're yet to do a cmdlet mapping for the Azure AD Preview module. How ever this tutorial: [Assign Azure AD roles in PIM](https://learn.microsoft.com/en-us/powershell/microsoftgraph/tutorial-pim?view=graph-powershell-1.0) can guide you on the cmdlets available for privileged role assignments. Let me know if you have any follow up queries.
