### ISSUE TITLE
Get-Credential documentation is bad which caused problem in section: Using client secret credentials

### ISSUE THREAD

**Issue by IN-jwink** [MicrosoftDocs/microsoftgraph-docs-powershell#329]
[Enter feedback here]

In section Using client secret credentials, -Credential should be used and NOT -UserName because Username is part of a parameterset that requires -Message.  This stems from the fact that no one bothered to mention this in the documentation for Get-Credential so one error in a document carried through to problems in another.  

Both the documentation for Get-Credential  Parameter: UserName needs to be corrected and this documents use of Get-Credential .

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 26caa942-e06a-6467-3a31-fa19104801f7
* Version Independent ID: 1f00beaa-439f-9e27-81de-7a35cccca4e8
* Content: [Using Microsoft Graph PowerShell authentication commands](https://learn.microsoft.com/en-us/powershell/microsoftgraph/authentication-commands?view=graph-powershell-1.0)
* Content Source: [microsoftgraph/docs-conceptual/authentication-commands.md](https://github.com/MicrosoftDocs/microsoftgraph-docs-powershell/blob/live/microsoftgraph/docs-conceptual/authentication-commands.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph-powershell**
* GitHub Login: @msewaweru
* Microsoft Alias: **eunicewaweru**

**Comment by msewaweru** [comment]
Hi @CarolKigoonya - requesting for your guidance on this issue and what do update we need to do to resolve this.

**Comment by IN-jwink** [comment]
Change this line:
$ClientSecretCredential = Get-Credential -Username "Client_Id"

To this:
$ClientSecretCredential = Get-Credential -Credential "Client_Id"

Because the documentation for Get-Credential didn't tell you that -UserName is part of a parameter set which requires you to provide text via a MESSAGE parameter to ask yourself why you are providing a credential.
-Credential also pre-fills the UserName box, without requiring a message.

This is confirmed in PS 5.1.  I did not test to see if behavior is somehow different in PS 7.x.

**Comment by IN-jwink** [comment]
Apologies, I thought you were asking me for clarification

**Comment by msewaweru** [comment]
No worries, @IN-jwink. Your input makes it a lot easier. Appreciate it.

**Comment by IN-jwink** [comment]
![image](https://github.com/MicrosoftDocs/microsoftgraph-docs-powershell/assets/48688761/0fc30ad7-0d7b-4ceb-83b5-22a2ca3694dd)
In Powershell 5.1, if I use -Credential, the next step is password.


![image](https://github.com/MicrosoftDocs/microsoftgraph-docs-powershell/assets/48688761/f74ce3a7-1688-4031-af3f-873dbe75e992)
When using Powershell 5.1, if I use -Username, I am forced to enter data for a required -Message parameter before continuing.  

I am guessing that you are using a newer Powershell and the cmdlets don't match functionally between them?

**Comment by IN-jwink** [comment]
![image](https://github.com/MicrosoftDocs/microsoftgraph-docs-powershell/assets/48688761/2ede1889-040a-4694-96f0-1cfc21497b36)

**Comment by msewaweru** [comment]
Thanks @IN-jwink for the clarification. I will retest this using PowerShell 5.1 and update the docs so that users are not confused the functionality differences in the 2 versions. Thanks.

**Comment by msewaweru** [comment]
Docs update complete.
