### ISSUE TITLE
Conceptual doc for `-Select` is not showing the right example

### ISSUE THREAD

**Issue by peombwa** [MicrosoftDocs/microsoftgraph-docs-powershell#357]
The `-Select` example for the conceptual doc at https://learn.microsoft.com/en-us/powershell/microsoftgraph/use-query-parameters?view=graph-powershell-1.0#select-parameter does not show the use of `-Select/-Property` parameter on the command.

The content should also be updated to use `-Property` as the parameter since `-Select` is an alias.

### Current Example
``` powershell
Get-MgUser | Select Id, DisplayName
```
### Correct Example
``` powershell
Get-MgUser -Property Id, DisplayName | Select Id, DisplayName
```

**Comment by msewaweru** [comment]
Thanks, @peombwa for highlighting this. Help me understand the difference. When I run the 2 examples I get the same result. :)

<img width="418" alt="image" src="https://github.com/MicrosoftDocs/microsoftgraph-docs-powershell/assets/73849846/2c07bef5-8d2d-48a8-a15f-9c8dfb9b76f3">

**Comment by peombwa** [comment]
@msewaweru, the doc talks about `OData system query options`. OData's `$select` equivalent in the SDK is `-Property`, which is aliased to `-Select`. The example shown in the doc is for PowerShell's `| Select-Object` command (alias `| Select`), not `-Property`. [-Property](https://learn.microsoft.com/en-us/powershell/module/microsoft.graph.users/get-mguser?view=graph-powershell-1.0#-property) vs [Select-Object](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/select-object?view=powershell-7.3)
