### ISSUE TITLE
For all examples imported from the Graph API docs, update the title to match what's on the Graph API docs.

### ISSUE THREAD

**Issue by msewaweru** [MicrosoftDocs/microsoftgraph-docs-powershell#358]
**Current title for Add-MgApplicationKey**

Example 1: Using the Add-MgApplicationKey Cmdlet

**Title on the Graph API docs**

Example 1: Add a new key credential to an application

**Comment by timayabi2020** [comment]
@msewaweru These two PRs: https://github.com/microsoftgraph/msgraph-sdk-powershell/pull/2212 and https://github.com/microsoftgraph/msgraph-sdk-powershell/pull/2217 will address this issue during the next refresh run which is expected to be on Thursday this week

**Comment by timayabi2020** [comment]
This has been resolved by this PR: https://github.com/MicrosoftDocs/microsoftgraph-docs-powershell/pull/364
