### ISSUE TITLE
Missing commandlet mapping for DirectorySetting and DirectorySettingTemplate

### ISSUE THREAD

**Issue by bachoang** [MicrosoftDocs/microsoftgraph-docs-powershell#361]
The doc is missing the mapping for the following AzureAD commandlet for both DirectorySetting and DirectorySettingTemplate:

Get-AzureADDirectorySetting
Get-AzureADDirectorySettingTemplate
New-AzureADDirectorySetting
Remove-AzureADDirectorySetting
Set-AzureADDirectorySetting

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: dada1864-4eb3-a28d-7894-af6d352a0f54
* Version Independent ID: 4f4e8d2f-85ad-06bd-aee2-797f2b921a0a
* Content: [Find Azure AD and MSOnline cmdlets in Microsoft Graph PowerShell](https://learn.microsoft.com/en-us/powershell/microsoftgraph/azuread-msoline-cmdlet-map?view=graph-powershell-1.0)
* Content Source: [microsoftgraph/docs-conceptual/azuread-msoline-cmdlet-map.md](https://github.com/MicrosoftDocs/microsoftgraph-docs-powershell/blob/live/microsoftgraph/docs-conceptual/azuread-msoline-cmdlet-map.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph-powershell**
* GitHub Login: @msewaweru
* Microsoft Alias: **eunicewaweru**

**Comment by msewaweru** [comment]
Hi @bachoang - thanks for highlighting this.

This set of cmdlets fall under the Azure AD Preview module, whose map is currently work in progress. We should have a map for Azure AD Preview cmdlets in the coming weeks. Thanks.
