### ISSUE TITLE
`-ForceRefresh` is not supported in v2

### ISSUE THREAD

**Issue by peombwa** [MicrosoftDocs/microsoftgraph-docs-powershell#365]
The use of `-ForceRefresh` on `Connect-MgGraph` [was dropped in v2](https://github.com/microsoftgraph/msgraph-sdk-powershell/blob/dev/docs/upgrade-to-v2.md#connect-mggraph--forcerefresh). We should update the documentation at https://learn.microsoft.com/en-us/powershell/microsoftgraph/authentication-commands?view=graph-powershell-1.0#connecting-to-an-environment-as-a-different-identity to show `Connect-MgGraph -ContextScope Process` without the `-ForceRefresh` switch.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 26caa942-e06a-6467-3a31-fa19104801f7
* Version Independent ID: 1f00beaa-439f-9e27-81de-7a35cccca4e8
* Content: [Using Microsoft Graph PowerShell authentication commands](https://learn.microsoft.com/en-us/powershell/microsoftgraph/authentication-commands?view=graph-powershell-1.0)
* Content Source: [microsoftgraph/docs-conceptual/authentication-commands.md](https://github.com/MicrosoftDocs/microsoftgraph-docs-powershell/blob/live/microsoftgraph/docs-conceptual/authentication-commands.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph-powershell**
* GitHub Login: @msewaweru
* Microsoft Alias: **eunicewaweru**

**Comment by msewaweru** [comment]
Thanks @peombwa for highlighting this. I will action accordingly.
