### ISSUE TITLE
Add deprecation alert box/warning for legacy PowerShell (Configuring Group settings)

### ISSUE THREAD

**Issue by SteveMutungi254** [MicrosoftDocs/microsoftgraph-docs-powershell#370]
**Ask:**

Add a deprecation warning to the page - https://learn.microsoft.com/en-us/azure/active-directory/enterprise-users/groups-settings-cmdlets advising customers to use Microsoft Graph PowerShell - https://learn.microsoft.com/en-us/azure/active-directory/enterprise-users/groups-settings-v2-cmdlets.

**Comment by msewaweru** [comment]
Hi @SteveMutungi254 - for docs issues outside of this repo, please open the issues in the respective repos. You can use the feedback section at the bottom of the page you wanted updated to create an issue for it.

![image](https://github.com/MicrosoftDocs/microsoftgraph-docs-powershell/assets/73849846/43a72836-03f8-46c9-907e-5a7685e0e432)
