### ISSUE TITLE
Update Azure AD and MSOL June 30 2023 deprecation notice to reflect March 2024

### ISSUE THREAD

**Issue by SteveMutungi254** [MicrosoftDocs/microsoftgraph-docs-powershell#371]
Sample page with old messaging - https://learn.microsoft.com/en-us/azure/active-directory/roles/groups-assign-role?tabs=aad-powershell.

**Definition of Done:**

Update **ALL** the pages with the old messaging to this one.

![image](https://github.com/MicrosoftDocs/microsoftgraph-docs-powershell/assets/132555836/f369abea-ec80-44f5-acad-67687581d090)

Message to be replaced - sample.

![image](https://github.com/MicrosoftDocs/microsoftgraph-docs-powershell/assets/132555836/259aeeaf-040b-40bd-8e1f-7238822e3a81)

**Comment by msewaweru** [comment]
Hi @SteveMutungi254 - Thanks for highlighting this issue. Please indicate which docsets have the old messaging. It could be a different repo.

**Comment by SteveMutungi254** [comment]
Hi, @msewaweru : I have created a new issue in the respective doc set - https://github.com/MicrosoftDocs/azure-docs/issues/114747.
