### ISSUE TITLE
Add deprecation warning to the Active Directory roles pre-requisites page

### ISSUE THREAD

**Issue by SteveMutungi254** [MicrosoftDocs/microsoftgraph-docs-powershell#372]
**Ask:**

Add a deprecation warning box on the [Active Directory roles prerequisites page](https://github.com/MicrosoftDocs/azure-docs-pr/blob/main/articles/active-directory/roles/prerequisites.md) to discourage customers from taking dependencies on deprecated modules (Azure AD and MsOnline).

Another possibility is to remove the Azure AD and MsOnline installation guide (pending consultation with relevant stakeholders).

The deprecation box can be as highlighted below or even better.

![image](https://github.com/MicrosoftDocs/microsoftgraph-docs-powershell/assets/132555836/53bc4820-6fcb-4706-9ebf-4dce87214848)

**Comment by msewaweru** [comment]
Hi @SteveMutungi254 - for docs issues outside of this repo, please open the issues in the respective repos. Issues opened in this repo should have the repo scope.

**Comment by SteveMutungi254** [comment]
> Hi @SteveMutungi254 - for docs issues outside of this repo, please open the issues in the respective repos. Issues opened in this repo should have the repo scope.

Hi, @msewaweru : I have raised the issue in Azure Docs repo - https://github.com/MicrosoftDocs/azure-docs/issues/113768

Please validate if there is clarity on the issue raised, then I close this issue.

**Comment by msewaweru** [comment]
@SteveMutungi254 - The new issue is adequately described. Thanks.
