### ISSUE TITLE
Using client secret credentials

### ISSUE THREAD

**Issue by nukala29** [MicrosoftDocs/microsoftgraph-docs-powershell#375]
When I try this feature(Using client secret credentials) using the latest version of MS Graph with PowerShell 5.1 it is not working

Get-InstalledModule Microsoft.Graph
Version    Name                                Repository           Description
-------    ----                                ----------           -----------
2.4.0      Microsoft.Graph                     PSGallery            Microsoft Graph PowerShell module

After doing some research and updating to the Powershell 7 it is working as expected

Only this feature using secret is not working on PowerShell 5  as per the observation it only runs on PowerShell 7.So it should good idea to put a note, especially for this 
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 26caa942-e06a-6467-3a31-fa19104801f7
* Version Independent ID: 1f00beaa-439f-9e27-81de-7a35cccca4e8
* Content: [Using Microsoft Graph PowerShell authentication commands](https://learn.microsoft.com/en-us/powershell/microsoftgraph/authentication-commands?view=graph-powershell-1.0&source=docs)
* Content Source: [microsoftgraph/docs-conceptual/authentication-commands.md](https://github.com/MicrosoftDocs/microsoftgraph-docs-powershell/blob/live/microsoftgraph/docs-conceptual/authentication-commands.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph-powershell**
* GitHub Login: @msewaweru
* Microsoft Alias: **eunicewaweru**

**Comment by msewaweru** [comment]
Thank you, @nukala29 for highlighting this issue. I will be updating docs to capture this.

**Comment by msewaweru** [comment]
Closing this following the docs update.
