### ISSUE TITLE
Notes section in the reference content not clear.

### ISSUE THREAD

**Issue by msewaweru** [MicrosoftDocs/microsoftgraph-docs-powershell#38]
We have received complaints from customers on the formatting of the notes section which makes it hard to work with content there. Can this be corrected by improving the content at source level. @maisarissi 

Cc: @CelesteDG

**Comment by psignoret** [comment]
Also reported at https://www.reddit.com/r/AZURE/comments/18gh2w7/botched_formatting_on_microsoft_learn_for_ms/

**Comment by timayabi2020** [comment]
@csmulligan I think we can close this issue

**Comment by psignoret** [comment]
@timayabi2020 @csmulligan I still see strange formatting, for example here: https://learn.microsoft.com/en-us/powershell/module/microsoft.graph.beta.identity.governance/new-mgbetaentitlementmanagementaccesspackageassignmentpolicy?view=graph-powershell-beta

**Comment by timayabi2020** [comment]
Ok. @psignoret thanks for pointing this out.  It seems there are some cases that were not handled.

**Comment by csmulligan** [comment]
@psignoret thanks for reaching out. This is a known issue, and we’re working on a fix while also investigating ways to improve  this section of the documentation.  I’ll go ahead and close this issue for now, but please don’t hesitate to reach out if you require any further assistance.
Thanks again!
