### ISSUE TITLE
prerequisite of az cli not documented

### ISSUE THREAD

**Issue by drdamour** [MicrosoftDocs/microsoftgraph-docs-powershell#391]
I installed this in a powershell version that didn't have the the Az module installed and i got an error when trying to run Get-MgPolicyTokenIssuancePolicy about some class from the Az module not being found.  Maybe it was because i had AzureRM module installed in that powershell..not sure but the fact that this depends on the Az module should be called out i think.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cfa0d6a2-8795-2d70-8282-4ab8169c8b70
* Version Independent ID: 80d8d30e-9bc3-87c1-1f8f-70850a787b3c
* Content: [Install the Microsoft Graph PowerShell SDK](https://learn.microsoft.com/en-us/powershell/microsoftgraph/installation?view=graph-powershell-1.0)
* Content Source: [microsoftgraph/docs-conceptual/installation.md](https://github.com/MicrosoftDocs/microsoftgraph-docs-powershell/blob/live/microsoftgraph/docs-conceptual/installation.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph-powershell**
* GitHub Login: @msewaweru
* Microsoft Alias: **eunicewaweru**

**Comment by msewaweru** [comment]
@drdamour - please share the error you got here. We shouldn't have any dependency on the Az module that I'm aware of.

**Comment by drdamour** [comment]
![image](https://github.com/MicrosoftDocs/microsoftgraph-docs-powershell/assets/1514496/c724bd15-09a4-4fbf-aad6-b05997c6c8d7)

circled 1 is the error about unable to find Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet
ignore my typo crossed off
2 is me importing Az module
3 is shows i no longer received the error about missing Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet

thus it appears there is a dependency

**Comment by csmulligan** [comment]
Hi @SteveMutungi254 could you please confirm that we shouldn’t have any dependency on Azure CLI when running the Get-MgPolicyTokenIssuancePolicy cmdlet? Thank you.

**Comment by SteveMutungi254** [comment]
> Hi @SteveMutungi254 could you please confirm that we shouldn’t have any dependency on Azure CLI when running the Get-MgPolicyTokenIssuancePolicy cmdlet? Thank you.

We don't/shouldn't have any dependency on Azure CLI. From the error, it is clear that the user needs to issue `Connect-MgGraph` to authenticate.

**Comment by drdamour** [comment]
@SteveMutungi254 i think you're looking at the wrong thing/not close enough, check the one labeled 1, that's the depednecy...once i forced the import the error changed, that's what i am showing

**Comment by SteveMutungi254** [comment]
@drdamour : Kindly shoot me an email (entraposh@microsoft.com) for further follow up. We will update this issue with comments after the offline investigation. cc: @csmulligan .

**Comment by csmulligan** [comment]
@drdamour thanks for reaching out! Throughout 2024 we will be phasing out GitHub Issues as the feedback mechanism for content and replacing it with a new feedback system. For more information see: https://aka.ms/ContentUserFeedback.

I’ll go ahead and close this issue for now, but please don’t hesitate to reach out if you require any further assistance.
Thanks again!

**Comment by drdamour** [comment]
such a bad decision, my fav thing about docs was github issues driving them
