### ISSUE TITLE
Command fails with: property 'AdditionalProperties' does not exist on type  'microsoft.management..'

### ISSUE THREAD

**Issue by dennis-bgit** [MicrosoftDocs/microsoftgraph-docs-powershell#396]
i'm working on this script to export policies from one Microsoft tenant and re create them in another tenant.
the script is as follows:
`$compliancePolicies = Get-MgDeviceManagementDeviceCompliancePolicy`
`$configurationProfiles = Get-MgBetaDeviceManagementDeviceConfiguration`

`$exportcompliancePolicies = $compliancePolicies | Export-Clixml -Path $compliancePoliciesPath`
`$exportconfigurationProfiles = $configurationProfiles | Export-Clixml -Path $configurationProfilesPath`
`Disconnect-MgGraph`

`$importcompliancePolicies = Import-Clixml -Path $compliancePoliciesPath`
`$importconfigurationProfiles = Import-Clixml -Path $configurationProfilesPath`

`Connect-MgGraph -Scopes DeviceManagementConfiguration.ReadWrite.All`

`$importcompliancePolicies | New-MgDeviceManagementDeviceCompliancePolicy `

the last command fails with this error:

` New-MgDeviceManagementDeviceCompliancePolicy : The property 'AdditionalProperties' does not exist on type 
'microsoft.management.services.api.deviceComplianceDeviceOverview'. Make sure to only use property names that are defined by the type.
Status: 400 (BadRequest)
ErrorCode: ModelValidationFailure `

which is a bit puzzeling since your documentation has `[-AdditionalProperties <Hashtable>]` as the first option for the command.

if i check the "AdditionalProperties" for type, i get this:
`$importcompliancePolicies[0].AdditionalProperties.GetType()`

`IsPublic IsSerial Name                                     BaseType        `                                                                                                                                                                               
`True     True     Hashtable                                System.Object `

which seems to be in lien with what the documentation is asking for.

let me know what other information i can provide.
I've tried the beta version of graph and it fails with the exact error. 
it also fails creating the configuration profiles (New-MgBetaDeviceManagementDeviceConfiguration)

**Comment by msewaweru** [comment]
Transferring issue to the SDK repo as it's not docs related.
