### ISSUE TITLE
Incorrect example in step 4

### ISSUE THREAD

**Issue by hnougher** [MicrosoftDocs/microsoftgraph-docs-powershell#411]
In step 4 it uses a comma separated list for the scope.
As mentioned elsewhere in the document, it needs to be a space-separated list.

Side-note: dangerously enough, Graph API does not check for correct values in the scope.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 38dd83e6-c20d-157a-dbd6-5d8d5c4e4f1b
* Version Independent ID: 1a50c1a6-2a00-3543-d28e-1ebdc5762fe4
* Content: [Grant and revoke delegated permissions programmatically in Azure AD](https://learn.microsoft.com/en-us/powershell/microsoftgraph/tutorial-grant-delegated-api-permissions?view=graph-powershell-1.0)
* Content Source: [microsoftgraph/docs-conceptual/tutorial-grant-delegated-api-permissions.md](https://github.com/MicrosoftDocs/microsoftgraph-docs-powershell/blob/live/microsoftgraph/docs-conceptual/tutorial-grant-delegated-api-permissions.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph-powershell**
* GitHub Login: @msewaweru
* Microsoft Alias: **eunicewaweru**

**Comment by csmulligan** [comment]
Hi @hnougher thank you so much for pointing this out. We've updated the article and changes should be published shortly. This issue will close automatically once the changes are merged. 
Thanks again!

**Comment by csmulligan** [comment]
#sign-off
