### ISSUE TITLE
Incorrect reference to "Description" property

### ISSUE THREAD

**Issue by sathumat** [MicrosoftDocs/microsoftgraph-docs-powershell#414]
For the cmdlet New-MgPolicyClaimMappingPolicy, "Description" is mentioned as a supported property. However, this property does not exist. I verified the cmdlet and seeing an error when using this property. Link to the cmdlet reference doc: https://learn.microsoft.com/en-us/powershell/module/microsoft.graph.identity.signins/new-mgpolicyclaimmappingpolicy?view=graph-powershell-1.0

The reference to "Description" property needs to be removed in both syntax and parameters sections.

**Comment by csmulligan** [comment]
@sathumat and @timayabi2020 thanks so much for your suggestions. I've added this to an internal work item for tracking. I'll go ahead and close this issue, but changes to the article are in the works. 
Thanks again!
