### ISSUE TITLE
 The example cited for using a client secret in the context of unattended operation is an interactive prompt!

### ISSUE THREAD

**Issue by chucklebrother** [MicrosoftDocs/microsoftgraph-docs-powershell#417]
The example cited for using a client secret in the context of unattended operation is an interactive prompt! Is this a joke? There's reference to the get-credential documentation, and an alternative is possible, but instead we have an example which will be useless to anyone trying to use this mechanism for it's intended purposes.

I feel like the worlds leading software company could do better.

https://learn.microsoft.com/en-us/powershell/microsoftgraph/authentication-commands?view=graph-powershell-1.0#using-client-secret-credentials

I have spent 10 minutes looking on the reference documentation and come up with:

```
$User = <Application (client) ID>
$PWord = ConvertTo-SecureString -String <Client Secret> -AsPlainText -Force
$ClientSecretCredential = New-Object -TypeName System.Management.Automation.PSCredential -ArgumentList $User, $PWord

Connect-MgGraph -TenantId "Tenant_Id" -ClientSecretCredential $ClientSecretCredential

```

Now, imagine everyone who ever reads this document losing 10minutes of their lives/employers-productivity (delete according you where your allegiances lie).

Hopefully you can see the value to the world in providing relevant examples.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 26caa942-e06a-6467-3a31-fa19104801f7
* Version Independent ID: 1f00beaa-439f-9e27-81de-7a35cccca4e8
* Content: [Using Microsoft Graph PowerShell authentication commands](https://learn.microsoft.com/en-us/powershell/microsoftgraph/authentication-commands?view=graph-powershell-1.0)
* Content Source: [microsoftgraph/docs-conceptual/authentication-commands.md](https://github.com/MicrosoftDocs/microsoftgraph-docs-powershell/blob/live/microsoftgraph/docs-conceptual/authentication-commands.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph-powershell**
* GitHub Login: @msewaweru
* Microsoft Alias: **eunicewaweru**

**Comment by msewaweru** [comment]
Thanks, @chucklebrother for highlighting the issue.
Adding @timayabi2020 @peombwa @CarolKigoonya for review.

**Comment by csmulligan** [comment]
Hi @chucklebrother, thank you so much for pointing this out and helping us improve the documentation. I’ve added this to an internal work item for tracking, and changes should be published shortly. I’ll go ahead and close this issue, but rest assured that changes to the article are in progress. 
Thanks again!
