### ISSUE TITLE
why has https://github.com/microsoftgraph/microsoft-graph-docs-contrib/issues/515 been closed, without any changes to the main page?

### ISSUE THREAD

**Issue by anwarmahmood1** [MicrosoftDocs/microsoftgraph-docs-powershell#462]
I go the notification two weeks ago, but I know changes take time to propagate. 

I've just checked, and it still says 'admin account'. In issue 515 this has been made more precise, but that hasn't been published.

please publish the clarification.

raising a new incident because I can't reopen https://github.com/microsoftgraph/microsoft-graph-docs-contrib/issues/515

really disappointing it's taking literally years to get to this stage, then it's closed without publishing the detail, and I have to  waste everyone's time by creating a NEW issue.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1249c655-3885-5a2d-1e70-191bd11640ce
* Version Independent ID: ec51b113-d125-f517-0bbd-35cc3073af2f
* Content: [Get started with the Microsoft Graph PowerShell SDK](https://learn.microsoft.com/en-us/powershell/microsoftgraph/get-started?view=graph-powershell-1.0)
* Content Source: [microsoftgraph/docs-conceptual/get-started.md](https://github.com/MicrosoftDocs/microsoftgraph-docs-powershell/blob/live/microsoftgraph/docs-conceptual/get-started.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph-powershell**
* GitHub Login: @msewaweru
* Microsoft Alias: **eunicewaweru**

**Comment by SteveMutungi254** [comment]
@anwarmahmood1 : The changes were merged. Kindly confirm if the changes are as per your expectation.

![image](https://github.com/MicrosoftDocs/microsoftgraph-docs-powershell/assets/132555836/992ded07-7ebd-495b-9cf8-07c9c92e993d)

**Comment by csmulligan** [comment]
As the changes have been merged, I am closing this issue. Please feel free to reopen it if needed. Thank you.
