### ISSUE TITLE
Azure Ad policy commands available in v1.0

### ISSUE THREAD

**Issue by nukala29** [MicrosoftDocs/microsoftgraph-docs-powershell#483]
[Enter feedback here]

As per the belwo doc 
https://learn.microsoft.com/en-us/graph/api/resources/policy-overview?view=graph-rest-1.0

Ploicy commands are vailble in v1.0  please upadte it form best to v1.0 cutsomer can use it
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: dada1864-4eb3-a28d-7894-af6d352a0f54
* Version Independent ID: 4f4e8d2f-85ad-06bd-aee2-797f2b921a0a
* Content: [Find Azure AD and MSOnline cmdlets in Microsoft Graph PowerShell](https://learn.microsoft.com/en-us/powershell/microsoftgraph/azuread-msoline-cmdlet-map?view=graph-powershell-1.0)
* Content Source: [microsoftgraph/docs-conceptual/azuread-msoline-cmdlet-map.md](https://github.com/MicrosoftDocs/microsoftgraph-docs-powershell/blob/live/microsoftgraph/docs-conceptual/azuread-msoline-cmdlet-map.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph-powershell**
* GitHub Login: @msewaweru
* Microsoft Alias: **eunicewaweru**

**Comment by csmulligan** [comment]
Hi @nukala29 thank you for reaching out. The article was recently updated. Could you please clarify which policy commandlets are missing? Thank you!

**Comment by csmulligan** [comment]
I'm closing the issue, please re-open it if needed. 
Thank you.
