### ISSUE TITLE
Please add comment to this to include the install-module "Install-Module Microsoft.Graph.Beta.Reports"

### ISSUE THREAD

**Issue by raidbighead** [MicrosoftDocs/microsoftgraph-docs-powershell#484]
with the installation of this module, we are missing the Install-Module Microsoft.Graph.Beta.Reports as part of the base install. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cfa0d6a2-8795-2d70-8282-4ab8169c8b70
* Version Independent ID: 80d8d30e-9bc3-87c1-1f8f-70850a787b3c
* Content: [Install the Microsoft Graph PowerShell SDK](https://learn.microsoft.com/en-us/powershell/microsoftgraph/installation?view=graph-powershell-1.0)
* Content Source: [microsoftgraph/docs-conceptual/installation.md](https://github.com/MicrosoftDocs/microsoftgraph-docs-powershell/blob/live/microsoftgraph/docs-conceptual/installation.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph-powershell**
* GitHub Login: @msewaweru
* Microsoft Alias: **eunicewaweru**

**Comment by csmulligan** [comment]
Hi @raidbighead thank you so much for pointing this out and helping us improve the documentation. I've moved this issue to an internal work item for tracking. 
I'll go ahead and close this issue, but changes to the article are in the works. 
Thanks again!
