### ISSUE TITLE
Uninstall is missing -AllVersions

### ISSUE THREAD

**Issue by JohanForngren** [MicrosoftDocs/microsoftgraph-docs-powershell#497]
```powershell
# This should be replaced
Get-InstalledModule Microsoft.Graph.* | ? Name -ne "Microsoft.Graph.Authentication" | Uninstall-Module
Uninstall-Module Microsoft.Graph.Authentication
# with the following to remove all versions:
Get-InstalledModule Microsoft.Graph.* | ? Name -ne "Microsoft.Graph.Authentication"  | Uninstall-Module -AllVersions
Uninstall-Module Microsoft.Graph.Authentication -AllVersions
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cfa0d6a2-8795-2d70-8282-4ab8169c8b70
* Version Independent ID: 80d8d30e-9bc3-87c1-1f8f-70850a787b3c
* Content: [Install the Microsoft Graph PowerShell SDK](https://learn.microsoft.com/en-us/powershell/microsoftgraph/installation?view=graph-powershell-1.0#uninstalling-the-sdk)
* Content Source: [microsoftgraph/docs-conceptual/installation.md](https://github.com/MicrosoftDocs/microsoftgraph-docs-powershell/blob/live/microsoftgraph/docs-conceptual/installation.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph-powershell**
* GitHub Login: @msewaweru
* Microsoft Alias: **eunicewaweru**

**Comment by csmulligan** [comment]
Thank you for reaching out @JohanForngren. I have requested the engineering team to review the pull request, and I will update this issue with any feedback or changes.

**Comment by csmulligan** [comment]
Hi @JohanForngren, thank you for passing along your workaround for this issue. The PR was approved and merged.
Thank you again!
