### ISSUE TITLE
Article on granting API permissions programmatically should mention directory roles that allow it  

### ISSUE THREAD

**Issue by psignoret** [MicrosoftDocs/microsoftgraph-docs-powershell#523]
For Microsoft Graph app roles (application permissions) (https://learn.microsoft.com/en-us/powershell/microsoftgraph/tutorial-grant-app-only-api-permissions?view=graph-powershell-1.0), one of the following built-in roles:

* Global Administrator
* Privileged Role Administrator

For Microsoft Graph delegated permissions (https://learn.microsoft.com/en-us/powershell/microsoftgraph/tutorial-grant-delegated-api-permissions?view=graph-powershell-1.0), one of the following:

* Global Administrator
* Privileged Role Administrator
* Application Administrator
* Cloud Application Administrator

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 61275359-27f4-e2cd-9ded-3ed06095c43c
* Version Independent ID: 38d5e91f-c320-84eb-0209-97c9a7ca3652
* Content: [Grant application permissions programmatically in Microsoft Entra ID](https://learn.microsoft.com/en-us/powershell/microsoftgraph/tutorial-grant-app-only-api-permissions?view=graph-powershell-1.0)
* Content Source: [microsoftgraph/docs-conceptual/tutorial-grant-app-only-api-permissions.md](https://github.com/MicrosoftDocs/microsoftgraph-docs-powershell/blob/live/microsoftgraph/docs-conceptual/tutorial-grant-app-only-api-permissions.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph-powershell**
* GitHub Login: @msewaweru
* Microsoft Alias: **eunicewaweru**

**Comment by msewaweru** [comment]
Hi @psignoret - thanks for catching that.

I have created [a PR](https://github.com/MicrosoftDocs/microsoftgraph-docs-powershell/pull/540) to make this update.

I will proceed to close this issue.
