### ISSUE TITLE
The authentication samples cannot work

### ISSUE THREAD

**Issue by plonialmoni** [MicrosoftDocs/microsoftgraph-docs-powershell#524]
It appears they use a depreciated API, I cannot find documentation so far for a current equivalent for MS Graph with Intune.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1249c655-3885-5a2d-1e70-191bd11640ce
* Version Independent ID: ec51b113-d125-f517-0bbd-35cc3073af2f
* Content: [Get started with the Microsoft Graph PowerShell SDK](https://learn.microsoft.com/en-us/powershell/microsoftgraph/get-started?view=graph-powershell-1.0)
* Content Source: [microsoftgraph/docs-conceptual/get-started.md](https://github.com/MicrosoftDocs/microsoftgraph-docs-powershell/blob/live/microsoftgraph/docs-conceptual/get-started.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph-powershell**
* GitHub Login: @msewaweru
* Microsoft Alias: **eunicewaweru**

**Comment by msewaweru** [comment]
Hi @plonialmoni - Thanks for raising this issue. Please clarify what error you are getting and the steps to reproduce.
