### ISSUE TITLE
Commandlet mapping for Set-AzureADUserExtension is wrong

### ISSUE THREAD

**Issue by bachoang** [MicrosoftDocs/microsoftgraph-docs-powershell#528]
This page lists the MS Graph PowerShell commandlet for Set-AzureADUserExtension is Update-MgUserExtension.  This is wrong.  Update-MgUserExtension is for open extensions type (https://learn.microsoft.com/en-us/graph/extensibility-open-users?tabs=http) while the Set-AzureADUserExtension is for updating the user's onPremisesExtensionAttribute collection.  They are completely different attributes.  The equivalent commandlet should be Update-MgUser.

Example:
Set-AzureADUserExtension -ObjectId <UserID> -ExtensionName "extensionAttribute8" -ExtensionValue "abc"

The equivalent in MS Graph PowerShell would be:
$params = @{
 onPremisesExtensionAttributes = @{
  extensionAttribute8 = "abc"
 }
}
 
Update-MgBetaUser -UserId $userId -BodyParameter $params

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: dada1864-4eb3-a28d-7894-af6d352a0f54
* Version Independent ID: 4f4e8d2f-85ad-06bd-aee2-797f2b921a0a
* Content: [Find Azure AD and MSOnline cmdlets in Microsoft Graph PowerShell](https://learn.microsoft.com/en-us/powershell/microsoftgraph/azuread-msoline-cmdlet-map?view=graph-powershell-1.0)
* Content Source: [microsoftgraph/docs-conceptual/azuread-msoline-cmdlet-map.md](https://github.com/MicrosoftDocs/microsoftgraph-docs-powershell/blob/live/microsoftgraph/docs-conceptual/azuread-msoline-cmdlet-map.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph-powershell**
* GitHub Login: @msewaweru
* Microsoft Alias: **eunicewaweru**

**Comment by msewaweru** [comment]
Thanks, @bachoang for highlighting this issue.

I have [a work item](https://dev.azure.com/msft-skilling/Content/_queries/edit/258572/?queryId=a1978685-ad26-41e8-8ce7-042148b9ad4f) tracking this issue and [a PR](https://github.com/MicrosoftDocs/microsoftgraph-docs-powershell/pull/541) that's ready for review.

Proceeding to close this issue.
