### ISSUE TITLE
Incorrect Installation Validation cmdlet

### ISSUE THREAD

**Issue by delgadoa1** [MicrosoftDocs/microsoftgraph-docs-powershell#530]
After following the instructions for the installation, the validation command of Get-InstalledModule Microsoft.Graph, does not work and throws an error: "PackageManagement\Get-Package : No match was found for the specified search criteria and module names 'Microsoft.Graph'."

It seems like the correct cmdlet is Get-InstalledModule MsGraph

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cfa0d6a2-8795-2d70-8282-4ab8169c8b70
* Version Independent ID: 80d8d30e-9bc3-87c1-1f8f-70850a787b3c
* Content: [Install the Microsoft Graph PowerShell SDK](https://learn.microsoft.com/en-us/powershell/microsoftgraph/installation?view=graph-powershell-1.0)
* Content Source: [microsoftgraph/docs-conceptual/installation.md](https://github.com/MicrosoftDocs/microsoftgraph-docs-powershell/blob/live/microsoftgraph/docs-conceptual/installation.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph-powershell**
* GitHub Login: @msewaweru
* Microsoft Alias: **eunicewaweru**

**Comment by msewaweru** [comment]
Hi @delgadoa1 - here is the output I get when I run the same command on my end. Please check if the installtion process run successfully. If yes, you can uninstall the module and reinstall it afresh.

![image](https://github.com/MicrosoftDocs/microsoftgraph-docs-powershell/assets/73849846/ed2cadf1-0006-48f5-bd4c-ce7facd07c6b)

Proceeding to close this issue.
